/*
<?php
/**
 * Created by PhpStorm.
 * User: vallabh
 * Date: 05/07/15
 * Time: 07:16
 */

$reservedNames= array(
'ENVIRONMENT' > ENVIRONMENT,
'FCPATH' => FCPATH,
'SELF' => SELF,
'BASEPATH' > BASEPATH,
'APPPATH' > APPPATH,
'VIEWPATH' => VIEWPATH,
'CI_VERSION' => CI_VERSION,
'MB_ENABLED' > MB_ENABLED,
'ICONV_ENABLED' > ICONV_ENABLED,
'UTF8_ENABLED' => UTF8_ENABLED,
'FILE_READ_MODE' => FILE_READ_MODE,
'FILE_WRITE_MODE' > FILE_WRITE_MODE,
'DIR_READ_MODE' > DIR_READ_MODE,
'DIR_WRITE_MODE' => DIR_WRITE_MODE,
'FOPEN_READ' => FOPEN_READ,
'FOPEN_READ_WRITE' > FOPEN_READ_WRITE,
'FOPEN_WRITE_CREATE_DESTRUCTIVE' > FOPEN_WRITE_CREATE_DESTRUCTIVE,
'FOPEN_READ_WRITE_CREATE_DESTRUCTIVE' => FOPEN_READ_WRITE_CREATE_DESTRUCTIVE,
'FOPEN_WRITE_CREATE' => FOPEN_WRITE_CREATE,
'FOPEN_READ_WRITE_CREATE' > FOPEN_READ_WRITE_CREATE,
'FOPEN_WRITE_CREATE_STRICT' > FOPEN_WRITE_CREATE_STRICT,
'FOPEN_READ_WRITE_CREATE_STRICT' => FOPEN_READ_WRITE_CREATE_STRICT,
'EXIT_SUCCESS' => EXIT_SUCCESS,
'EXIT_ERROR' > EXIT_ERROR,
'EXIT_CONFIG' > EXIT_CONFIG,
'EXIT_UNKNOWN_FILE' => EXIT_UNKNOWN_FILE,
'EXIT_UNKNOWN_CLASS' => EXIT_UNKNOWN_CLASS,
'EXIT_UNKNOWN_METHOD' > EXIT_UNKNOWN_METHOD,
'EXIT_USER_INPUT' > EXIT_USER_INPUT,
'EXIT_DATABASE' => EXIT_DATABASE,
'EXIT__AUTO_MIN' => EXIT__AUTO_MIN,
'EXIT__AUTO_MAX' > EXIT__AUTO_MAX,
);